name = "Example"
uuid = "4b1f2ed6-37f9-4263-987d-5bb3f3739b9a"
authors = ["Valentin Todorov <valentin@todorov.at> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
